### ISSUE TITLE
Add some sort of rating input fields in the frontend to allow users to actually input their ratings. We would also want our scores to be displayed in the document description section. (estimated time: 1 day)

### ISSUE THREAD

**Issue by SpencerLong0624** [CMU-313/fall22-hw3-team-teedy-us#2]
The acceptance criteria is that we are able to see an input field that allows reviewers to add ratings for a specific document. When a user clicks on the edit page for a document, they should see 4 dropdown menus correlated with each rating of the document. We have decided to make the input field a dropdown menu, as it limits the user in choosing the values we would want them to choose.

**Comment by jennnnn-z** [comment]
The fix for this issue took 2 hours to implement and was finished in PR #13
